name: 'Git Message'
description: 'Get the git message associated with the current SHA'
inputs:
  sha:
    description: 'sha of the commit (defaults to the GITHUB_SHA environment variable)'
    required: false
outputs:
  git-message:
    description: 'The git message'
  title:
    description: 'The title of the git-message, i.e. the first line'
  body:
    description: 'The body of the git-message, i.e. everything but the first line'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'git-commit'
  color: 'gray-dark'
